services:
  web:
    build: .
    command: sh -c "sleep 10 && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn mycity.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  daphne:
    build: .
    command: sh -c "sleep 10 && daphne -b 0.0.0.0 -p 8001 mycity.asgi:application"
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - media:/app/media
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
    driver: local
  staticfiles:
    driver: local
  media:
    driver: local