services:
  - type: web
    name: mycity-web
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: mycity-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: mycity-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

  - type: web
    name: mycity-daphne
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    dockerCommand: daphne -b 0.0.0.0 -p 8001 mycity.asgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: mycity-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: mycity-redis
          property: connectionString
      - key: SECRET_KEY
        sync: false

  - type: redis
    name: mycity-redis
    plan: free
    ipAllowList: ["0.0.0.0/0"] # Allow all IPs for testing

databases:
  - name: mycity-db
    plan: free